In [94]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_json('data/original/Basketball_women.json', lines=True)

df.iloc[0]

_id                                                      abrahta01w
firstName                                                    Tajama
middleName                                                    Ethia
lastName                                                    Abraham
fullGivenName                                        Tajama Abraham
nameNick                                                     TJ,Taj
pos                                                               C
height                                                           74
weight                                                          190
college                                           George Washington
birthDate                                                1975-09-27
birthCity                                                  St,Croix
birthCountry                                                    ISV
highSchool                                               Kecoughtan
hsCity                                                      Hampton
hsState                                                          VA
hsCountry                                                       USA
players_teams     [{'year': 1997, 'tmID': 'SAC', 'games': 28, 'm...
awards_players                                                   []
Name: 0, dtype: object

In [38]:
df_high_schools = pd.DataFrame(index=df['highSchool'].unique())
df_high_schools.to_csv('data/transformed/high_schools.csv', index_label="HighSchool")
df_high_schools

Empty DataFrame
Columns: []
Index: [Kecoughtan, Petrogradskoi N86, Anacostia Senior, Lee's Summit, Moapa Valley, None, Malcolm X. Shabazz, Orrville, Martin Luther King, Santa Ynez, Flint Central, Monessen, Sacred Heart Academy, St. Peters, Carondelet, Minas Gerais, Lee Central, Capitol, Saunders Secondary School, Roaring Fork, Beavercreek, 47 Bishkek, Mission Bay, Benton Harbor, Parker, The Linsley School, Southwood, Window Rock, Northwest Christian Academy, Christ the King, University, East Forsyth, Parkview, Lawrence, West Bakersfield, Florence, Huntington, McClain, Fairfield, Jurii Gagarin, Bertie, Mirani State, Ulysses S. Grant, Southeast Bulloch, Woodward Academy, Summerville, Martinsburg, Palos Verdes, Bob Jones, Bolton, St. Pius X Catholic, Whitney Young, Horizon, Eastside, DeSoto, McKeesport Area, Stevenson / Duncanville, McDonough School, South Mecklenburg, J. Frank Dobie, Resurrection, Senn Metropolitan Academy, Lee Summit North, St. Johns College, East Bay, Westside, Charlestown, Nathaniel Narbonne, Wawasee, Fairfax, The Bullis School, Brookhaven, Independence, Princeton, Franklin County, Terrell County, Sentinel, Elk City, Edgewood, Linden, Bridgeport Central, Christ the King (jr-sr), Ben Davis, Northeast, Muir, St. Joseph's Academy, Summerfield, Bryn Mawr, Gulliver Prep, Cedar Falls, Phoebus, John Marshall, Beech Grove, Cinco Ranch, Ouachita, Warren Central, R. Nelson Snider, Clinton, Waterloo West, St. Agnes, ...]

[242 rows x 0 columns]

Node types are:
- Player
- College
- High school
- Team

In [34]:
df_colleges = pd.DataFrame(index=df['college'].unique())
df_colleges.to_csv('data/transformed/colleges.csv', index_label="College")
df_colleges

Empty DataFrame
Columns: []
Index: [George Washington, Connecticut, Texas A&M, New Mexico, None, Rutgers, Ohio State, UNC Charlotte, California-Santa Barbara, DePaul, Notre Dame, Arizona State, Brigham Young, Vanderbilt, Wisconsin, Old Dominion, Tennessee, Stanford, none, Northeastern, North Carolina, Louisiana State, Kansas, Pepperdine, Syracuse, Boise State, California, Georgia, Duke, Washington, Academy of Sport Moscow, Arizona, Indiana, Montana State, Florida International, Rice, Illinois, Iowa, Colorado, St. Joseph's, Maine, UCLA, Miami (FL), Auburn, Louisiana Tech, Missouri, Illinois State, Virginia, Michigan State, Oral Roberts, Texas Tech, U. Western Sydney, Long Beach State, Texas, Furman, Penn State, Georgetown, Maryland, Alabama, Tulane, Eastern Michigan, Central Florida CC, USC, Oklahoma, George Mason, North Carolina State, UC Santa Barbara, Arkansas, Middle Tennessee State, Australian Institute of Sport, Kansas State, Mercer, Purdue, Baylor, Colorado State, Oregon, Florida State, Nebraska, Kentucky, Temple, Evangel, James Madison, Harvard, Southern Mississippi, Georgia Tech, Iowa State, Liberty, Duquesne, Lamar, Virginia Tech, Howard, Mississippi, North Carolina State (jr-sr), South Carolina, Houston, Florida Atlantic, South Florida, Xavier, Florida, Northern Illinois, ...]

[161 rows x 0 columns]

In [39]:
# These relationships are complex, we will add them later with Cypher code
df_players = df.drop(columns=['players_teams', 'awards_players'])
df_players = df_players.set_index('_id')
df_players.to_csv('data/transformed/players.csv')
df_players

,firstName,middleName,lastName,fullGivenName,nameNick,pos,height,weight,college,birthDate,birthCity,birthCountry,highSchool,hsCity,hsState,hsCountry
_id,,,,,,,,,,,,,,,,
abrahta01w,Tajama,Ethia,Abraham,Tajama Abraham,"TJ,Taj",C,74,190,George Washington,1975-09-27,"St,Croix",ISV,Kecoughtan,Hampton,VA,USA
abrossv01w,Svetlana,Olegovna,Abrosimova,Svetlana Abrosimova,"Svet,Sveta",F,74,169,Connecticut,1980-07-09,St. Petersburg,URS,Petrogradskoi N86,St. Petersburg,None,RUS
adairje01w,Jessica,Elizabeth,Adair,Jessica Adair,None,C,76,197,George Washington,1986-12-19,Washington,USA,Anacostia Senior,Washington,DC,USA
adamsda01w,Danielle,E.,Adams,Danielle Adams,None,F-C,73,239,Texas A&M,1989-02-19,Kansas City,USA,Lee's Summit,Lee's Summit,MO,USA
adamsjo01w,Jordan,None,Adams,Jordan Adams,None,C,75,180,New Mexico,1981-05-24,Las Vegas,USA,Moapa Valley,Overton,NV,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zellosh01w,Shavonte,None,Zellous,Shavonte Zellous,None,G,70,155,Pittsburgh,1986-08-28,None,None,None,None,None,None
zhengha01w,Haixia,None,Zheng,Haixia Zheng,None,C,80,254,None,1967-03-07,Tuocheng,CHN,None,None,None,None
zierddo99w,Don,None,Zierden,Don Zierden,None,None,0,0,None,0000-00-00,None,None,None,None,None,None
zirkozu01w,Zuzana,None,Zirkova,Zuzana Zirkova,None,G,69,145,None,1980-06-06,Bojnice,TCH,None,None,None,None
zollsh01w,Sharnee',None,Zoll,Sharnee' Zoll,None,G,67,148,Virginia,1986-07-11,None,None,None,None,None,None

## Players' teams

In [106]:
tmp = df[['_id', 'players_teams']].explode('players_teams', ignore_index=True)
df_r_teams = pd.json_normalize(tmp['players_teams']).astype({'year': pd.Int64Dtype(), 'games': pd.Int64Dtype(), 'minutes': pd.Int64Dtype(), 'points': pd.Int64Dtype(), 'steals': pd.Int64Dtype(), 'blocks': pd.Int64Dtype()})
df_r_teams['playerId'] = tmp['_id']
df_r_teams.dropna(inplace=True)
df_r_teams.to_csv('data/transformed/players_teams.csv', index_label="relId")

### Awards

In [136]:
tmp = df[['_id', 'awards_players']].explode('awards_players', ignore_index=True)
df_r_awards = pd.json_normalize(tmp['awards_players']).astype({'year': pd.Int64Dtype()})
df_r_awards['playerId'] = tmp['_id']
df_r_awards.dropna(inplace=True)
df_r_awards.to_csv('data/transformed/awards.csv', index_label="relId")
df_r_awards

                                      award  year    pos    playerId
8                         Coach of the Year  2010  Coach  aglerbr99w
33         WNBA Finals Most Valuable Player  2011    G-F  augusse01w
67                     WNBA All-Decade Team  2006      G   birdsu01w
68                 Kim Perrot Sportsmanship  2011      G   birdsu01w
84   WNBA All Decade Team Honorable Mention  2006      G  boltoru01w
88                  Sixth Woman of the Year  2010    G-F  bonnede01w
89                  Sixth Woman of the Year  2011      F  bonnede01w
150                    WNBA All-Decade Team  2006      F  catchta01w
151            Defensive Player of the Year  2010      F  catchta01w
152                Kim Perrot Sportsmanship  2010      F  catchta01w
153                    Most Valuable Player  2011      F  catchta01w
154        WNBA Finals Most Valuable Player  2012      F  catchta01w
155            Defensive Player of the Year  2012      F  catchta01w
166                      Rookie of the Year  2010      C  charlti01w
167                Peak Performer: Rebounds  2010      C  charlti01w
168                Peak Performer: Rebounds  2011      C  charlti01w
169                    Most Valuable Player  2012      C  charlti01w
170                Peak Performer: Rebounds  2012      C  charlti01w
203                    WNBA All-Decade Team  2006      G  coopecy01w
286            Defensive Player of the Year  2011      C  fowlesy01w
340                    WNBA All-Decade Team  2006      C  griffyo01w
388  WNBA All Decade Team Honorable Mention  2006      F  holdsch01w
416                    WNBA All-Decade Team  2006      C  jacksla01w
417                    Most Valuable Player  2010      F  jacksla01w
418        WNBA Finals Most Valuable Player  2010      F  jacksla01w
491                Kim Perrot Sportsmanship  2012      G  lawsoka01w
507                    WNBA All-Decade Team  2006      C  leslili01w
564                  Peak Performer: Points  2012    G-F  mccouan01w
584                    Most Improved Player  2010      G  mitchle01w
592                 Sixth Woman of the Year  2012      G  montgre01w
596                      Rookie of the Year  2011      F  moorema01w
632                      Rookie of the Year  2012      F  ogwumnn01w
658  WNBA All Decade Team Honorable Mention  2006      G  penicti01w
659                 Peak Performer: Assists  2010      G  penicti01w
713                Kim Perrot Sportsmanship  2011      C  rileyru01w
777                    WNBA All-Decade Team  2006      F  smithka01w
792                    WNBA All-Decade Team  2006      G  staleda01w
823                    WNBA All-Decade Team  2006      F  swoopsh01w
831  WNBA All Decade Team Honorable Mention  2006      G  tauradi01w
832                  Peak Performer: Points  2010    G-F  tauradi01w
833                  Peak Performer: Points  2011    G-F  tauradi01w
855                    WNBA All-Decade Team  2006      F  thompti01w
862                    Most Improved Player  2012      G  tolivkr01w
881                    Most Improved Player  2011      C  vaughki01w
905  WNBA All Decade Team Honorable Mention  2006      G  weathte01w
911                 Peak Performer: Assists  2011      G  whaleli01w
912                 Peak Performer: Assists  2012      G  whaleli01w